//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwinfieldApi.TwinfieldFinderService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.twinfield.com/", ConfigurationName="TwinfieldFinderService.FinderSoap")]
    public interface FinderSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/Search", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TwinfieldApi.TwinfieldFinderService.SearchResponse Search(TwinfieldApi.TwinfieldFinderService.SearchRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/Search", ReplyAction="*")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldFinderService.SearchResponse> SearchAsync(TwinfieldApi.TwinfieldFinderService.SearchRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    public partial class Header : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sessionIDField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
                this.RaisePropertyChanged("SessionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    public partial class FinderData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int totalRowsField;
        
        private string[] columnsField;
        
        private string[][] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TotalRows {
            get {
                return this.totalRowsField;
            }
            set {
                this.totalRowsField = value;
                this.RaisePropertyChanged("TotalRows");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public string[] Columns {
            get {
                return this.columnsField;
            }
            set {
                this.columnsField = value;
                this.RaisePropertyChanged("Columns");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    public partial class MessageOfErrorCodes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageType typeField;
        
        private string textField;
        
        private ErrorCodes codeField;
        
        private string[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MessageType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ErrorCodes Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public string[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("Parameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    public enum MessageType {
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        Informational,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    public enum ErrorCodes {
        
        /// <remarks/>
        NoAccessToOffice,
        
        /// <remarks/>
        OptionNotAllowed,
        
        /// <remarks/>
        InvalidBooleanOptionValue,
        
        /// <remarks/>
        InvalidIntegerOptionValue,
        
        /// <remarks/>
        InvalidDecimalOptionValue,
        
        /// <remarks/>
        InvalidEnumerationOptionValue,
        
        /// <remarks/>
        OptionValueOutOfRange,
        
        /// <remarks/>
        ParameterOutOfRange,
        
        /// <remarks/>
        InvalidFinderType,
        
        /// <remarks/>
        ParameterTooSmall,
        
        /// <remarks/>
        OptionLevelMandatoryForSectionTEQ,
        
        /// <remarks/>
        OptionICIncompatableWithOptionHidden,
        
        /// <remarks/>
        InvalidDateTimeOptionLength,
        
        /// <remarks/>
        InvalidDateTimeOptionValue,
        
        /// <remarks/>
        InvalidDateTimeOptionOutOfRange,
        
        /// <remarks/>
        OptionMandatory,
        
        /// <remarks/>
        DisableAccessRulesNotAllowed,
        
        /// <remarks/>
        Option1MandatoryIfOption2IsUsed,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Search", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class SearchRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldApi.TwinfieldFinderService.Header Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public string type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=1)]
        public string pattern;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=2)]
        public int field;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=3)]
        public int firstRow;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=4)]
        public int maxRows;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] options;
        
        public SearchRequest() {
        }
        
        public SearchRequest(TwinfieldApi.TwinfieldFinderService.Header Header, string type, string pattern, int field, int firstRow, int maxRows, string[][] options) {
            this.Header = Header;
            this.type = type;
            this.pattern = pattern;
            this.field = field;
            this.firstRow = firstRow;
            this.maxRows = maxRows;
            this.options = options;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class SearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldApi.TwinfieldFinderService.MessageOfErrorCodes[] SearchResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=1)]
        public TwinfieldApi.TwinfieldFinderService.FinderData data;
        
        public SearchResponse() {
        }
        
        public SearchResponse(TwinfieldApi.TwinfieldFinderService.MessageOfErrorCodes[] SearchResult, TwinfieldApi.TwinfieldFinderService.FinderData data) {
            this.SearchResult = SearchResult;
            this.data = data;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FinderSoapChannel : TwinfieldApi.TwinfieldFinderService.FinderSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FinderSoapClient : System.ServiceModel.ClientBase<TwinfieldApi.TwinfieldFinderService.FinderSoap>, TwinfieldApi.TwinfieldFinderService.FinderSoap {
        
        public FinderSoapClient() {
        }
        
        public FinderSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FinderSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinderSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinderSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldFinderService.SearchResponse TwinfieldApi.TwinfieldFinderService.FinderSoap.Search(TwinfieldApi.TwinfieldFinderService.SearchRequest request) {
            return base.Channel.Search(request);
        }
        
        public TwinfieldApi.TwinfieldFinderService.MessageOfErrorCodes[] Search(TwinfieldApi.TwinfieldFinderService.Header Header, string type, string pattern, int field, int firstRow, int maxRows, string[][] options, out TwinfieldApi.TwinfieldFinderService.FinderData data) {
            TwinfieldApi.TwinfieldFinderService.SearchRequest inValue = new TwinfieldApi.TwinfieldFinderService.SearchRequest();
            inValue.Header = Header;
            inValue.type = type;
            inValue.pattern = pattern;
            inValue.field = field;
            inValue.firstRow = firstRow;
            inValue.maxRows = maxRows;
            inValue.options = options;
            TwinfieldApi.TwinfieldFinderService.SearchResponse retVal = ((TwinfieldApi.TwinfieldFinderService.FinderSoap)(this)).Search(inValue);
            data = retVal.data;
            return retVal.SearchResult;
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldFinderService.SearchResponse> SearchAsync(TwinfieldApi.TwinfieldFinderService.SearchRequest request) {
            return base.Channel.SearchAsync(request);
        }
    }
}
