//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Twinfield_Webservices_Sample_C_sharp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://login.twinfield.com/webservices/session.asmx")]
        public string Twinfield_Webservices_Sample_C_sharp_TwinfieldSession_Session {
            get {
                return ((string)(this["Twinfield_Webservices_Sample_C_sharp_TwinfieldSession_Session"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://login.twinfield.com/webservices/processxml.asmx")]
        public string Twinfield_Webservices_Sample_C_sharp_TwinfieldProcessXml_ProcessXml {
            get {
                return ((string)(this["Twinfield_Webservices_Sample_C_sharp_TwinfieldProcessXml_ProcessXml"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://login.twinfield.com/webservices/finder.asmx")]
        public string Twinfield_Webservices_Sample_C_sharp_TwinfieldFinder_Finder {
            get {
                return ((string)(this["Twinfield_Webservices_Sample_C_sharp_TwinfieldFinder_Finder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://accounting.twinfield.com/webservices/session.asmx")]
        public string Twinfield_Webservices_Sample_C_sharp_TwinfieldClusterSession_Session {
            get {
                return ((string)(this["Twinfield_Webservices_Sample_C_sharp_TwinfieldClusterSession_Session"]));
            }
        }
    }
}
