//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwinfieldApi.TwinfieldBankBookService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Command", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldBankBookService.BankBookCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldBankBookService.CreateBankBook))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldBankBookService.ChangeBankBookName))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldBankBookService.ChangeBankBookShortName))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldBankBookService.ChangeBankBookBankAccount))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldBankBookService.ChangeBankBookGeneralLedgerAccount))]
    public partial class Command : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankBookCommand", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankBookService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldBankBookService.CreateBankBook))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldBankBookService.ChangeBankBookName))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldBankBookService.ChangeBankBookShortName))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldBankBookService.ChangeBankBookBankAccount))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldBankBookService.ChangeBankBookGeneralLedgerAccount))]
    public partial class BankBookCommand : TwinfieldApi.TwinfieldBankBookService.Command {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateBankBook", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankBookService")]
    [System.SerializableAttribute()]
    public partial class CreateBankBook : TwinfieldApi.TwinfieldBankBookService.BankBookCommand {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinfieldApi.TwinfieldBankBookService.BankAccount BankAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeneralLedgerAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldApi.TwinfieldBankBookService.BankAccount BankAccount {
            get {
                return this.BankAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.BankAccountField, value) != true)) {
                    this.BankAccountField = value;
                    this.RaisePropertyChanged("BankAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GeneralLedgerAccount {
            get {
                return this.GeneralLedgerAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneralLedgerAccountField, value) != true)) {
                    this.GeneralLedgerAccountField = value;
                    this.RaisePropertyChanged("GeneralLedgerAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangeBankBookName", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankBookService")]
    [System.SerializableAttribute()]
    public partial class ChangeBankBookName : TwinfieldApi.TwinfieldBankBookService.BankBookCommand {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangeBankBookShortName", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankBookService")]
    [System.SerializableAttribute()]
    public partial class ChangeBankBookShortName : TwinfieldApi.TwinfieldBankBookService.BankBookCommand {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortName {
            get {
                return this.ShortNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortNameField, value) != true)) {
                    this.ShortNameField = value;
                    this.RaisePropertyChanged("ShortName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangeBankBookBankAccount", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankBookService")]
    [System.SerializableAttribute()]
    public partial class ChangeBankBookBankAccount : TwinfieldApi.TwinfieldBankBookService.BankBookCommand {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinfieldApi.TwinfieldBankBookService.BankAccount BankAccountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldApi.TwinfieldBankBookService.BankAccount BankAccount {
            get {
                return this.BankAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.BankAccountField, value) != true)) {
                    this.BankAccountField = value;
                    this.RaisePropertyChanged("BankAccount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangeBankBookGeneralLedgerAccount", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankBookService")]
    [System.SerializableAttribute()]
    public partial class ChangeBankBookGeneralLedgerAccount : TwinfieldApi.TwinfieldBankBookService.BankBookCommand {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeneralLedgerAccountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GeneralLedgerAccount {
            get {
                return this.GeneralLedgerAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneralLedgerAccountField, value) != true)) {
                    this.GeneralLedgerAccountField = value;
                    this.RaisePropertyChanged("GeneralLedgerAccount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankAccount", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankBookService")]
    [System.SerializableAttribute()]
    public partial class BankAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        private string IbanField;
        
        private string NameField;
        
        private string NbicField;
        
        private string NumberField;
        
        private string ReferenceNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Bic {
            get {
                return this.BicField;
            }
            set {
                if ((object.ReferenceEquals(this.BicField, value) != true)) {
                    this.BicField = value;
                    this.RaisePropertyChanged("Bic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Iban {
            get {
                return this.IbanField;
            }
            set {
                if ((object.ReferenceEquals(this.IbanField, value) != true)) {
                    this.IbanField = value;
                    this.RaisePropertyChanged("Iban");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Nbic {
            get {
                return this.NbicField;
            }
            set {
                if ((object.ReferenceEquals(this.NbicField, value) != true)) {
                    this.NbicField = value;
                    this.RaisePropertyChanged("Nbic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ReferenceNumber {
            get {
                return this.ReferenceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceNumberField, value) != true)) {
                    this.ReferenceNumberField = value;
                    this.RaisePropertyChanged("ReferenceNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankBookServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankBookService")]
    [System.SerializableAttribute()]
    public partial class BankBookServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinfieldApi.TwinfieldBankBookService.BankBookServiceFaultCode CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldApi.TwinfieldBankBookService.BankBookServiceFaultCode Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankBookServiceFaultCode", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankBookService")]
    public enum BankBookServiceFaultCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BankBookNotFound = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BankBookAlreadyExists = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BankBookInvalidAccountSettings = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BankBookInvalidGeneralLedgerAccount = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BankBookAccountNumberMayNotBeChanged = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BankBookGeneralLedgerAccountMayNotBeChanged = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    [System.SerializableAttribute()]
    public partial class SecurityFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinfieldApi.TwinfieldBankBookService.SecurityFaultCode CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldApi.TwinfieldBankBookService.SecurityFaultCode Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityFaultCode", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    public enum SecurityFaultCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HeaderIsMissing = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessDenied = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LogonInvalid = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LogonDeleted = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LogonDisabled = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganisationInactive = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SmsSendFailed = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCluster = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SelectCompanyFailed = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidLogonServer = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SameUserIsAlreadyLoggedIn = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoggedOffByTwinfield = 11,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    [System.SerializableAttribute()]
    public partial class ValidationFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Query", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldBankBookService.GetBankBook))]
    public partial class Query : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBankBook", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankBookService")]
    [System.SerializableAttribute()]
    public partial class GetBankBook : TwinfieldApi.TwinfieldBankBookService.Query {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryResult", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldBankBookService.GetBankBookResult))]
    public partial class QueryResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBankBookResult", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankBookService")]
    [System.SerializableAttribute()]
    public partial class GetBankBookResult : TwinfieldApi.TwinfieldBankBookService.QueryResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinfieldApi.TwinfieldBankBookService.AutomaticBankProcessing AutomaticBankProcessingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinfieldApi.TwinfieldBankBookService.BankAccount BankAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeneralLedgerAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldApi.TwinfieldBankBookService.AutomaticBankProcessing AutomaticBankProcessing {
            get {
                return this.AutomaticBankProcessingField;
            }
            set {
                if ((object.ReferenceEquals(this.AutomaticBankProcessingField, value) != true)) {
                    this.AutomaticBankProcessingField = value;
                    this.RaisePropertyChanged("AutomaticBankProcessing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldApi.TwinfieldBankBookService.BankAccount BankAccount {
            get {
                return this.BankAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.BankAccountField, value) != true)) {
                    this.BankAccountField = value;
                    this.RaisePropertyChanged("BankAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GeneralLedgerAccount {
            get {
                return this.GeneralLedgerAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneralLedgerAccountField, value) != true)) {
                    this.GeneralLedgerAccountField = value;
                    this.RaisePropertyChanged("GeneralLedgerAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortName {
            get {
                return this.ShortNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortNameField, value) != true)) {
                    this.ShortNameField = value;
                    this.RaisePropertyChanged("ShortName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutomaticBankProcessing", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankBookService")]
    [System.SerializableAttribute()]
    public partial class AutomaticBankProcessing : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ProcessDirectDebitsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ProcessPaymentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ProcessStatementsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinfieldApi.TwinfieldBankBookService.AutomaticBankProcessingSignUpState SignUpStateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ProcessDirectDebits {
            get {
                return this.ProcessDirectDebitsField;
            }
            set {
                if ((this.ProcessDirectDebitsField.Equals(value) != true)) {
                    this.ProcessDirectDebitsField = value;
                    this.RaisePropertyChanged("ProcessDirectDebits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ProcessPayments {
            get {
                return this.ProcessPaymentsField;
            }
            set {
                if ((this.ProcessPaymentsField.Equals(value) != true)) {
                    this.ProcessPaymentsField = value;
                    this.RaisePropertyChanged("ProcessPayments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ProcessStatements {
            get {
                return this.ProcessStatementsField;
            }
            set {
                if ((this.ProcessStatementsField.Equals(value) != true)) {
                    this.ProcessStatementsField = value;
                    this.RaisePropertyChanged("ProcessStatements");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldApi.TwinfieldBankBookService.AutomaticBankProcessingSignUpState SignUpState {
            get {
                return this.SignUpStateField;
            }
            set {
                if ((this.SignUpStateField.Equals(value) != true)) {
                    this.SignUpStateField = value;
                    this.RaisePropertyChanged("SignUpState");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutomaticBankProcessingSignUpState", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankBookService")]
    public enum AutomaticBankProcessingSignUpState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactive = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.twinfield.com/", ConfigurationName="TwinfieldBankBookService.BankBookService")]
    public interface BankBookService {
        
        // CODEGEN: Generating message contract since the operation Process is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/BankBookService/Process", ReplyAction="http://www.twinfield.com/BankBookService/ProcessResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TwinfieldApi.TwinfieldBankBookService.BankBookServiceFault), Action="http://www.twinfield.com/BankBookService/ProcessBankBookServiceFaultFault", Name="BankBookServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankBookService")]
        [System.ServiceModel.FaultContractAttribute(typeof(TwinfieldApi.TwinfieldBankBookService.SecurityFault), Action="http://www.twinfield.com/BankBookService/ProcessSecurityFaultFault", Name="SecurityFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
        [System.ServiceModel.FaultContractAttribute(typeof(TwinfieldApi.TwinfieldBankBookService.ValidationFault), Action="http://www.twinfield.com/BankBookService/ProcessValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
        TwinfieldApi.TwinfieldBankBookService.ProcessResponse Process(TwinfieldApi.TwinfieldBankBookService.CommandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/BankBookService/Process", ReplyAction="http://www.twinfield.com/BankBookService/ProcessResponse")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldBankBookService.ProcessResponse> ProcessAsync(TwinfieldApi.TwinfieldBankBookService.CommandRequest request);
        
        // CODEGEN: Generating message contract since the operation Query is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/BankBookService/Query", ReplyAction="http://www.twinfield.com/BankBookService/QueryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TwinfieldApi.TwinfieldBankBookService.ValidationFault), Action="http://www.twinfield.com/BankBookService/QueryValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
        [System.ServiceModel.FaultContractAttribute(typeof(TwinfieldApi.TwinfieldBankBookService.SecurityFault), Action="http://www.twinfield.com/BankBookService/QuerySecurityFaultFault", Name="SecurityFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
        [System.ServiceModel.FaultContractAttribute(typeof(TwinfieldApi.TwinfieldBankBookService.BankBookServiceFault), Action="http://www.twinfield.com/BankBookService/QueryBankBookServiceFaultFault", Name="BankBookServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankBookService")]
        TwinfieldApi.TwinfieldBankBookService.QueryResponse Query(TwinfieldApi.TwinfieldBankBookService.QueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/BankBookService/Query", ReplyAction="http://www.twinfield.com/BankBookService/QueryResponse")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldBankBookService.QueryResponse> QueryAsync(TwinfieldApi.TwinfieldBankBookService.QueryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CommandRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public string SessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldApi.TwinfieldBankBookService.Command Command;
        
        public CommandRequest() {
        }
        
        public CommandRequest(string SessionId, TwinfieldApi.TwinfieldBankBookService.Command Command) {
            this.SessionId = SessionId;
            this.Command = Command;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessResponse {
        
        public ProcessResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public string SessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldApi.TwinfieldBankBookService.Query Query;
        
        public QueryRequest() {
        }
        
        public QueryRequest(string SessionId, TwinfieldApi.TwinfieldBankBookService.Query Query) {
            this.SessionId = SessionId;
            this.Query = Query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldApi.TwinfieldBankBookService.QueryResult Result;
        
        public QueryResponse() {
        }
        
        public QueryResponse(TwinfieldApi.TwinfieldBankBookService.QueryResult Result) {
            this.Result = Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BankBookServiceChannel : TwinfieldApi.TwinfieldBankBookService.BankBookService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankBookServiceClient : System.ServiceModel.ClientBase<TwinfieldApi.TwinfieldBankBookService.BankBookService>, TwinfieldApi.TwinfieldBankBookService.BankBookService {
        
        public BankBookServiceClient() {
        }
        
        public BankBookServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankBookServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankBookServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankBookServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldBankBookService.ProcessResponse TwinfieldApi.TwinfieldBankBookService.BankBookService.Process(TwinfieldApi.TwinfieldBankBookService.CommandRequest request) {
            return base.Channel.Process(request);
        }
        
        public void Process(string SessionId, TwinfieldApi.TwinfieldBankBookService.Command Command) {
            TwinfieldApi.TwinfieldBankBookService.CommandRequest inValue = new TwinfieldApi.TwinfieldBankBookService.CommandRequest();
            inValue.SessionId = SessionId;
            inValue.Command = Command;
            TwinfieldApi.TwinfieldBankBookService.ProcessResponse retVal = ((TwinfieldApi.TwinfieldBankBookService.BankBookService)(this)).Process(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldBankBookService.ProcessResponse> TwinfieldApi.TwinfieldBankBookService.BankBookService.ProcessAsync(TwinfieldApi.TwinfieldBankBookService.CommandRequest request) {
            return base.Channel.ProcessAsync(request);
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldBankBookService.ProcessResponse> ProcessAsync(string SessionId, TwinfieldApi.TwinfieldBankBookService.Command Command) {
            TwinfieldApi.TwinfieldBankBookService.CommandRequest inValue = new TwinfieldApi.TwinfieldBankBookService.CommandRequest();
            inValue.SessionId = SessionId;
            inValue.Command = Command;
            return ((TwinfieldApi.TwinfieldBankBookService.BankBookService)(this)).ProcessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldBankBookService.QueryResponse TwinfieldApi.TwinfieldBankBookService.BankBookService.Query(TwinfieldApi.TwinfieldBankBookService.QueryRequest request) {
            return base.Channel.Query(request);
        }
        
        public TwinfieldApi.TwinfieldBankBookService.QueryResult Query(string SessionId, TwinfieldApi.TwinfieldBankBookService.Query Query1) {
            TwinfieldApi.TwinfieldBankBookService.QueryRequest inValue = new TwinfieldApi.TwinfieldBankBookService.QueryRequest();
            inValue.SessionId = SessionId;
            inValue.Query = Query1;
            TwinfieldApi.TwinfieldBankBookService.QueryResponse retVal = ((TwinfieldApi.TwinfieldBankBookService.BankBookService)(this)).Query(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldBankBookService.QueryResponse> TwinfieldApi.TwinfieldBankBookService.BankBookService.QueryAsync(TwinfieldApi.TwinfieldBankBookService.QueryRequest request) {
            return base.Channel.QueryAsync(request);
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldBankBookService.QueryResponse> QueryAsync(string SessionId, TwinfieldApi.TwinfieldBankBookService.Query Query) {
            TwinfieldApi.TwinfieldBankBookService.QueryRequest inValue = new TwinfieldApi.TwinfieldBankBookService.QueryRequest();
            inValue.SessionId = SessionId;
            inValue.Query = Query;
            return ((TwinfieldApi.TwinfieldBankBookService.BankBookService)(this)).QueryAsync(inValue);
        }
    }
}
