//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwinfieldApi.TwinfieldProcessXmlService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.twinfield.com/", ConfigurationName="TwinfieldProcessXmlService.ProcessXmlSoap")]
    public interface ProcessXmlSoap {
        
        // CODEGEN: Generating message contract since message ProcessXmlStringRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/ProcessXmlString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlStringResponse ProcessXmlString(TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/ProcessXmlString", ReplyAction="*")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlStringResponse> ProcessXmlStringAsync(TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlStringRequest request);
        
        // CODEGEN: Generating message contract since message ProcessXmlDocumentRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/ProcessXmlDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlDocumentResponse ProcessXmlDocument(TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/ProcessXmlDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlDocumentResponse> ProcessXmlDocumentAsync(TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlDocumentRequest request);
        
        // CODEGEN: Generating message contract since message ProcessXmlCompressedRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/ProcessXmlCompressed", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlCompressedResponse ProcessXmlCompressed(TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlCompressedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/ProcessXmlCompressed", ReplyAction="*")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlCompressedResponse> ProcessXmlCompressedAsync(TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlCompressedRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    public partial class Header : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sessionIDField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
                this.RaisePropertyChanged("SessionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessXmlString", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class ProcessXmlStringRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldApi.TwinfieldProcessXmlService.Header Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public string xmlRequest;
        
        public ProcessXmlStringRequest() {
        }
        
        public ProcessXmlStringRequest(TwinfieldApi.TwinfieldProcessXmlService.Header Header, string xmlRequest) {
            this.Header = Header;
            this.xmlRequest = xmlRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessXmlStringResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class ProcessXmlStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public string ProcessXmlStringResult;
        
        public ProcessXmlStringResponse() {
        }
        
        public ProcessXmlStringResponse(string ProcessXmlStringResult) {
            this.ProcessXmlStringResult = ProcessXmlStringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessXmlDocument", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class ProcessXmlDocumentRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldApi.TwinfieldProcessXmlService.Header Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public System.Xml.XmlNode xmlRequest;
        
        public ProcessXmlDocumentRequest() {
        }
        
        public ProcessXmlDocumentRequest(TwinfieldApi.TwinfieldProcessXmlService.Header Header, System.Xml.XmlNode xmlRequest) {
            this.Header = Header;
            this.xmlRequest = xmlRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessXmlDocumentResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class ProcessXmlDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public System.Xml.XmlNode ProcessXmlDocumentResult;
        
        public ProcessXmlDocumentResponse() {
        }
        
        public ProcessXmlDocumentResponse(System.Xml.XmlNode ProcessXmlDocumentResult) {
            this.ProcessXmlDocumentResult = ProcessXmlDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessXmlCompressed", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class ProcessXmlCompressedRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldApi.TwinfieldProcessXmlService.Header Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] xmlRequest;
        
        public ProcessXmlCompressedRequest() {
        }
        
        public ProcessXmlCompressedRequest(TwinfieldApi.TwinfieldProcessXmlService.Header Header, byte[] xmlRequest) {
            this.Header = Header;
            this.xmlRequest = xmlRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessXmlCompressedResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class ProcessXmlCompressedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ProcessXmlCompressedResult;
        
        public ProcessXmlCompressedResponse() {
        }
        
        public ProcessXmlCompressedResponse(byte[] ProcessXmlCompressedResult) {
            this.ProcessXmlCompressedResult = ProcessXmlCompressedResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProcessXmlSoapChannel : TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProcessXmlSoapClient : System.ServiceModel.ClientBase<TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlSoap>, TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlSoap {
        
        public ProcessXmlSoapClient() {
        }
        
        public ProcessXmlSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProcessXmlSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessXmlSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessXmlSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlStringResponse TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlSoap.ProcessXmlString(TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlStringRequest request) {
            return base.Channel.ProcessXmlString(request);
        }
        
        public string ProcessXmlString(TwinfieldApi.TwinfieldProcessXmlService.Header Header, string xmlRequest) {
            TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlStringRequest inValue = new TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlStringRequest();
            inValue.Header = Header;
            inValue.xmlRequest = xmlRequest;
            TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlStringResponse retVal = ((TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlSoap)(this)).ProcessXmlString(inValue);
            return retVal.ProcessXmlStringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlStringResponse> TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlSoap.ProcessXmlStringAsync(TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlStringRequest request) {
            return base.Channel.ProcessXmlStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlStringResponse> ProcessXmlStringAsync(TwinfieldApi.TwinfieldProcessXmlService.Header Header, string xmlRequest) {
            TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlStringRequest inValue = new TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlStringRequest();
            inValue.Header = Header;
            inValue.xmlRequest = xmlRequest;
            return ((TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlSoap)(this)).ProcessXmlStringAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlDocumentResponse TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlSoap.ProcessXmlDocument(TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlDocumentRequest request) {
            return base.Channel.ProcessXmlDocument(request);
        }
        
        public System.Xml.XmlNode ProcessXmlDocument(TwinfieldApi.TwinfieldProcessXmlService.Header Header, System.Xml.XmlNode xmlRequest) {
            TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlDocumentRequest inValue = new TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlDocumentRequest();
            inValue.Header = Header;
            inValue.xmlRequest = xmlRequest;
            TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlDocumentResponse retVal = ((TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlSoap)(this)).ProcessXmlDocument(inValue);
            return retVal.ProcessXmlDocumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlDocumentResponse> TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlSoap.ProcessXmlDocumentAsync(TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlDocumentRequest request) {
            return base.Channel.ProcessXmlDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlDocumentResponse> ProcessXmlDocumentAsync(TwinfieldApi.TwinfieldProcessXmlService.Header Header, System.Xml.XmlNode xmlRequest) {
            TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlDocumentRequest inValue = new TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlDocumentRequest();
            inValue.Header = Header;
            inValue.xmlRequest = xmlRequest;
            return ((TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlSoap)(this)).ProcessXmlDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlCompressedResponse TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlSoap.ProcessXmlCompressed(TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlCompressedRequest request) {
            return base.Channel.ProcessXmlCompressed(request);
        }
        
        public byte[] ProcessXmlCompressed(TwinfieldApi.TwinfieldProcessXmlService.Header Header, byte[] xmlRequest) {
            TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlCompressedRequest inValue = new TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlCompressedRequest();
            inValue.Header = Header;
            inValue.xmlRequest = xmlRequest;
            TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlCompressedResponse retVal = ((TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlSoap)(this)).ProcessXmlCompressed(inValue);
            return retVal.ProcessXmlCompressedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlCompressedResponse> TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlSoap.ProcessXmlCompressedAsync(TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlCompressedRequest request) {
            return base.Channel.ProcessXmlCompressedAsync(request);
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlCompressedResponse> ProcessXmlCompressedAsync(TwinfieldApi.TwinfieldProcessXmlService.Header Header, byte[] xmlRequest) {
            TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlCompressedRequest inValue = new TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlCompressedRequest();
            inValue.Header = Header;
            inValue.xmlRequest = xmlRequest;
            return ((TwinfieldApi.TwinfieldProcessXmlService.ProcessXmlSoap)(this)).ProcessXmlCompressedAsync(inValue);
        }
    }
}
