//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwinfieldApi.TwinfieldSessionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.twinfield.com/", ConfigurationName="TwinfieldSessionService.SessionSoap")]
    public interface SessionSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/Logon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TwinfieldApi.TwinfieldSessionService.LogonResponse Logon(TwinfieldApi.TwinfieldSessionService.LogonRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/Logon", ReplyAction="*")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldSessionService.LogonResponse> LogonAsync(TwinfieldApi.TwinfieldSessionService.LogonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/SmsLogon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TwinfieldApi.TwinfieldSessionService.SmsLogonResponse SmsLogon(TwinfieldApi.TwinfieldSessionService.SmsLogonRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/SmsLogon", ReplyAction="*")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldSessionService.SmsLogonResponse> SmsLogonAsync(TwinfieldApi.TwinfieldSessionService.SmsLogonRequest request);
        
        // CODEGEN: Generating message contract since message SmsSendCodeRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/SmsSendCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TwinfieldApi.TwinfieldSessionService.SmsSendCodeResponse SmsSendCode(TwinfieldApi.TwinfieldSessionService.SmsSendCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/SmsSendCode", ReplyAction="*")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldSessionService.SmsSendCodeResponse> SmsSendCodeAsync(TwinfieldApi.TwinfieldSessionService.SmsSendCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/ChangePassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TwinfieldApi.TwinfieldSessionService.ChangePasswordResponse ChangePassword(TwinfieldApi.TwinfieldSessionService.ChangePasswordRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/ChangePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldSessionService.ChangePasswordResponse> ChangePasswordAsync(TwinfieldApi.TwinfieldSessionService.ChangePasswordRequest request);
        
        // CODEGEN: Generating message contract since message SelectCompanyRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/SelectCompany", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TwinfieldApi.TwinfieldSessionService.SelectCompanyResponse SelectCompany(TwinfieldApi.TwinfieldSessionService.SelectCompanyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/SelectCompany", ReplyAction="*")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldSessionService.SelectCompanyResponse> SelectCompanyAsync(TwinfieldApi.TwinfieldSessionService.SelectCompanyRequest request);
        
        // CODEGEN: Generating message contract since message KeepAliveRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/KeepAlive", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TwinfieldApi.TwinfieldSessionService.KeepAliveResponse KeepAlive(TwinfieldApi.TwinfieldSessionService.KeepAliveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/KeepAlive", ReplyAction="*")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldSessionService.KeepAliveResponse> KeepAliveAsync(TwinfieldApi.TwinfieldSessionService.KeepAliveRequest request);
        
        // CODEGEN: Generating message contract since message AbandonRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/Abandon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TwinfieldApi.TwinfieldSessionService.AbandonResponse Abandon(TwinfieldApi.TwinfieldSessionService.AbandonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/Abandon", ReplyAction="*")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldSessionService.AbandonResponse> AbandonAsync(TwinfieldApi.TwinfieldSessionService.AbandonRequest request);
        
        // CODEGEN: Generating message contract since message GetRoleRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/GetRole", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TwinfieldApi.TwinfieldSessionService.GetRoleResponse GetRole(TwinfieldApi.TwinfieldSessionService.GetRoleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/GetRole", ReplyAction="*")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldSessionService.GetRoleResponse> GetRoleAsync(TwinfieldApi.TwinfieldSessionService.GetRoleRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    public partial class Header : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sessionIDField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
                this.RaisePropertyChanged("SessionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    public enum LogonResult {
        
        /// <remarks/>
        Ok,
        
        /// <remarks/>
        Blocked,
        
        /// <remarks/>
        Untrusted,
        
        /// <remarks/>
        Invalid,
        
        /// <remarks/>
        Deleted,
        
        /// <remarks/>
        Disabled,
        
        /// <remarks/>
        OrganisationInactive,
        
        /// <remarks/>
        ClientInvalid,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    public enum LogonAction {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        SMSLogon,
        
        /// <remarks/>
        ChangePassword,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Logon", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class LogonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=2)]
        public string organisation;
        
        public LogonRequest() {
        }
        
        public LogonRequest(string user, string password, string organisation) {
            this.user = user;
            this.password = password;
            this.organisation = organisation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogonResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class LogonResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldApi.TwinfieldSessionService.Header Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldApi.TwinfieldSessionService.LogonResult LogonResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=1)]
        public TwinfieldApi.TwinfieldSessionService.LogonAction nextAction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=2)]
        public string cluster;
        
        public LogonResponse() {
        }
        
        public LogonResponse(TwinfieldApi.TwinfieldSessionService.Header Header, TwinfieldApi.TwinfieldSessionService.LogonResult LogonResult, TwinfieldApi.TwinfieldSessionService.LogonAction nextAction, string cluster) {
            this.Header = Header;
            this.LogonResult = LogonResult;
            this.nextAction = nextAction;
            this.cluster = cluster;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    public enum SMSLogonResult {
        
        /// <remarks/>
        Ok,
        
        /// <remarks/>
        Invalid,
        
        /// <remarks/>
        TimeOut,
        
        /// <remarks/>
        Disabled,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SmsLogon", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class SmsLogonRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldApi.TwinfieldSessionService.Header Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public string smsCode;
        
        public SmsLogonRequest() {
        }
        
        public SmsLogonRequest(TwinfieldApi.TwinfieldSessionService.Header Header, string smsCode) {
            this.Header = Header;
            this.smsCode = smsCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SmsLogonResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class SmsLogonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldApi.TwinfieldSessionService.SMSLogonResult SmsLogonResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=1)]
        public TwinfieldApi.TwinfieldSessionService.LogonAction nextAction;
        
        public SmsLogonResponse() {
        }
        
        public SmsLogonResponse(TwinfieldApi.TwinfieldSessionService.SMSLogonResult SmsLogonResult, TwinfieldApi.TwinfieldSessionService.LogonAction nextAction) {
            this.SmsLogonResult = SmsLogonResult;
            this.nextAction = nextAction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SmsSendCode", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class SmsSendCodeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldApi.TwinfieldSessionService.Header Header;
        
        public SmsSendCodeRequest() {
        }
        
        public SmsSendCodeRequest(TwinfieldApi.TwinfieldSessionService.Header Header) {
            this.Header = Header;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SmsSendCodeResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class SmsSendCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public int SmsSendCodeResult;
        
        public SmsSendCodeResponse() {
        }
        
        public SmsSendCodeResponse(int SmsSendCodeResult) {
            this.SmsSendCodeResult = SmsSendCodeResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    public enum ChangePasswordResult {
        
        /// <remarks/>
        Ok,
        
        /// <remarks/>
        Invalid,
        
        /// <remarks/>
        NotDifferent,
        
        /// <remarks/>
        NotSecure,
        
        /// <remarks/>
        Disabled,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangePassword", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class ChangePasswordRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldApi.TwinfieldSessionService.Header Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public string currentPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=1)]
        public string newPassword;
        
        public ChangePasswordRequest() {
        }
        
        public ChangePasswordRequest(TwinfieldApi.TwinfieldSessionService.Header Header, string currentPassword, string newPassword) {
            this.Header = Header;
            this.currentPassword = currentPassword;
            this.newPassword = newPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangePasswordResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class ChangePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldApi.TwinfieldSessionService.ChangePasswordResult ChangePasswordResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=1)]
        public TwinfieldApi.TwinfieldSessionService.LogonAction nextAction;
        
        public ChangePasswordResponse() {
        }
        
        public ChangePasswordResponse(TwinfieldApi.TwinfieldSessionService.ChangePasswordResult ChangePasswordResult, TwinfieldApi.TwinfieldSessionService.LogonAction nextAction) {
            this.ChangePasswordResult = ChangePasswordResult;
            this.nextAction = nextAction;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    public enum SelectCompanyResult {
        
        /// <remarks/>
        Ok,
        
        /// <remarks/>
        Invalid,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectCompany", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class SelectCompanyRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldApi.TwinfieldSessionService.Header Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public string company;
        
        public SelectCompanyRequest() {
        }
        
        public SelectCompanyRequest(TwinfieldApi.TwinfieldSessionService.Header Header, string company) {
            this.Header = Header;
            this.company = company;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectCompanyResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class SelectCompanyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldApi.TwinfieldSessionService.SelectCompanyResult SelectCompanyResult;
        
        public SelectCompanyResponse() {
        }
        
        public SelectCompanyResponse(TwinfieldApi.TwinfieldSessionService.SelectCompanyResult SelectCompanyResult) {
            this.SelectCompanyResult = SelectCompanyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KeepAlive", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class KeepAliveRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldApi.TwinfieldSessionService.Header Header;
        
        public KeepAliveRequest() {
        }
        
        public KeepAliveRequest(TwinfieldApi.TwinfieldSessionService.Header Header) {
            this.Header = Header;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KeepAliveResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class KeepAliveResponse {
        
        public KeepAliveResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Abandon", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class AbandonRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldApi.TwinfieldSessionService.Header Header;
        
        public AbandonRequest() {
        }
        
        public AbandonRequest(TwinfieldApi.TwinfieldSessionService.Header Header) {
            this.Header = Header;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AbandonResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class AbandonResponse {
        
        public AbandonResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRole", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class GetRoleRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldApi.TwinfieldSessionService.Header Header;
        
        public GetRoleRequest() {
        }
        
        public GetRoleRequest(TwinfieldApi.TwinfieldSessionService.Header Header) {
            this.Header = Header;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRoleResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class GetRoleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public string GetRoleResult;
        
        public GetRoleResponse() {
        }
        
        public GetRoleResponse(string GetRoleResult) {
            this.GetRoleResult = GetRoleResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SessionSoapChannel : TwinfieldApi.TwinfieldSessionService.SessionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SessionSoapClient : System.ServiceModel.ClientBase<TwinfieldApi.TwinfieldSessionService.SessionSoap>, TwinfieldApi.TwinfieldSessionService.SessionSoap {
        
        public SessionSoapClient() {
        }
        
        public SessionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SessionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldSessionService.LogonResponse TwinfieldApi.TwinfieldSessionService.SessionSoap.Logon(TwinfieldApi.TwinfieldSessionService.LogonRequest request) {
            return base.Channel.Logon(request);
        }
        
        public TwinfieldApi.TwinfieldSessionService.Header Logon(string user, string password, string organisation, out TwinfieldApi.TwinfieldSessionService.LogonResult LogonResult, out TwinfieldApi.TwinfieldSessionService.LogonAction nextAction, out string cluster) {
            TwinfieldApi.TwinfieldSessionService.LogonRequest inValue = new TwinfieldApi.TwinfieldSessionService.LogonRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.organisation = organisation;
            TwinfieldApi.TwinfieldSessionService.LogonResponse retVal = ((TwinfieldApi.TwinfieldSessionService.SessionSoap)(this)).Logon(inValue);
            LogonResult = retVal.LogonResult;
            nextAction = retVal.nextAction;
            cluster = retVal.cluster;
            return retVal.Header;
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldSessionService.LogonResponse> LogonAsync(TwinfieldApi.TwinfieldSessionService.LogonRequest request) {
            return base.Channel.LogonAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldSessionService.SmsLogonResponse TwinfieldApi.TwinfieldSessionService.SessionSoap.SmsLogon(TwinfieldApi.TwinfieldSessionService.SmsLogonRequest request) {
            return base.Channel.SmsLogon(request);
        }
        
        public TwinfieldApi.TwinfieldSessionService.SMSLogonResult SmsLogon(TwinfieldApi.TwinfieldSessionService.Header Header, string smsCode, out TwinfieldApi.TwinfieldSessionService.LogonAction nextAction) {
            TwinfieldApi.TwinfieldSessionService.SmsLogonRequest inValue = new TwinfieldApi.TwinfieldSessionService.SmsLogonRequest();
            inValue.Header = Header;
            inValue.smsCode = smsCode;
            TwinfieldApi.TwinfieldSessionService.SmsLogonResponse retVal = ((TwinfieldApi.TwinfieldSessionService.SessionSoap)(this)).SmsLogon(inValue);
            nextAction = retVal.nextAction;
            return retVal.SmsLogonResult;
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldSessionService.SmsLogonResponse> SmsLogonAsync(TwinfieldApi.TwinfieldSessionService.SmsLogonRequest request) {
            return base.Channel.SmsLogonAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldSessionService.SmsSendCodeResponse TwinfieldApi.TwinfieldSessionService.SessionSoap.SmsSendCode(TwinfieldApi.TwinfieldSessionService.SmsSendCodeRequest request) {
            return base.Channel.SmsSendCode(request);
        }
        
        public int SmsSendCode(TwinfieldApi.TwinfieldSessionService.Header Header) {
            TwinfieldApi.TwinfieldSessionService.SmsSendCodeRequest inValue = new TwinfieldApi.TwinfieldSessionService.SmsSendCodeRequest();
            inValue.Header = Header;
            TwinfieldApi.TwinfieldSessionService.SmsSendCodeResponse retVal = ((TwinfieldApi.TwinfieldSessionService.SessionSoap)(this)).SmsSendCode(inValue);
            return retVal.SmsSendCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldSessionService.SmsSendCodeResponse> TwinfieldApi.TwinfieldSessionService.SessionSoap.SmsSendCodeAsync(TwinfieldApi.TwinfieldSessionService.SmsSendCodeRequest request) {
            return base.Channel.SmsSendCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldSessionService.SmsSendCodeResponse> SmsSendCodeAsync(TwinfieldApi.TwinfieldSessionService.Header Header) {
            TwinfieldApi.TwinfieldSessionService.SmsSendCodeRequest inValue = new TwinfieldApi.TwinfieldSessionService.SmsSendCodeRequest();
            inValue.Header = Header;
            return ((TwinfieldApi.TwinfieldSessionService.SessionSoap)(this)).SmsSendCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldSessionService.ChangePasswordResponse TwinfieldApi.TwinfieldSessionService.SessionSoap.ChangePassword(TwinfieldApi.TwinfieldSessionService.ChangePasswordRequest request) {
            return base.Channel.ChangePassword(request);
        }
        
        public TwinfieldApi.TwinfieldSessionService.ChangePasswordResult ChangePassword(TwinfieldApi.TwinfieldSessionService.Header Header, string currentPassword, string newPassword, out TwinfieldApi.TwinfieldSessionService.LogonAction nextAction) {
            TwinfieldApi.TwinfieldSessionService.ChangePasswordRequest inValue = new TwinfieldApi.TwinfieldSessionService.ChangePasswordRequest();
            inValue.Header = Header;
            inValue.currentPassword = currentPassword;
            inValue.newPassword = newPassword;
            TwinfieldApi.TwinfieldSessionService.ChangePasswordResponse retVal = ((TwinfieldApi.TwinfieldSessionService.SessionSoap)(this)).ChangePassword(inValue);
            nextAction = retVal.nextAction;
            return retVal.ChangePasswordResult;
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldSessionService.ChangePasswordResponse> ChangePasswordAsync(TwinfieldApi.TwinfieldSessionService.ChangePasswordRequest request) {
            return base.Channel.ChangePasswordAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldSessionService.SelectCompanyResponse TwinfieldApi.TwinfieldSessionService.SessionSoap.SelectCompany(TwinfieldApi.TwinfieldSessionService.SelectCompanyRequest request) {
            return base.Channel.SelectCompany(request);
        }
        
        public TwinfieldApi.TwinfieldSessionService.SelectCompanyResult SelectCompany(TwinfieldApi.TwinfieldSessionService.Header Header, string company) {
            TwinfieldApi.TwinfieldSessionService.SelectCompanyRequest inValue = new TwinfieldApi.TwinfieldSessionService.SelectCompanyRequest();
            inValue.Header = Header;
            inValue.company = company;
            TwinfieldApi.TwinfieldSessionService.SelectCompanyResponse retVal = ((TwinfieldApi.TwinfieldSessionService.SessionSoap)(this)).SelectCompany(inValue);
            return retVal.SelectCompanyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldSessionService.SelectCompanyResponse> TwinfieldApi.TwinfieldSessionService.SessionSoap.SelectCompanyAsync(TwinfieldApi.TwinfieldSessionService.SelectCompanyRequest request) {
            return base.Channel.SelectCompanyAsync(request);
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldSessionService.SelectCompanyResponse> SelectCompanyAsync(TwinfieldApi.TwinfieldSessionService.Header Header, string company) {
            TwinfieldApi.TwinfieldSessionService.SelectCompanyRequest inValue = new TwinfieldApi.TwinfieldSessionService.SelectCompanyRequest();
            inValue.Header = Header;
            inValue.company = company;
            return ((TwinfieldApi.TwinfieldSessionService.SessionSoap)(this)).SelectCompanyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldSessionService.KeepAliveResponse TwinfieldApi.TwinfieldSessionService.SessionSoap.KeepAlive(TwinfieldApi.TwinfieldSessionService.KeepAliveRequest request) {
            return base.Channel.KeepAlive(request);
        }
        
        public void KeepAlive(TwinfieldApi.TwinfieldSessionService.Header Header) {
            TwinfieldApi.TwinfieldSessionService.KeepAliveRequest inValue = new TwinfieldApi.TwinfieldSessionService.KeepAliveRequest();
            inValue.Header = Header;
            TwinfieldApi.TwinfieldSessionService.KeepAliveResponse retVal = ((TwinfieldApi.TwinfieldSessionService.SessionSoap)(this)).KeepAlive(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldSessionService.KeepAliveResponse> TwinfieldApi.TwinfieldSessionService.SessionSoap.KeepAliveAsync(TwinfieldApi.TwinfieldSessionService.KeepAliveRequest request) {
            return base.Channel.KeepAliveAsync(request);
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldSessionService.KeepAliveResponse> KeepAliveAsync(TwinfieldApi.TwinfieldSessionService.Header Header) {
            TwinfieldApi.TwinfieldSessionService.KeepAliveRequest inValue = new TwinfieldApi.TwinfieldSessionService.KeepAliveRequest();
            inValue.Header = Header;
            return ((TwinfieldApi.TwinfieldSessionService.SessionSoap)(this)).KeepAliveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldSessionService.AbandonResponse TwinfieldApi.TwinfieldSessionService.SessionSoap.Abandon(TwinfieldApi.TwinfieldSessionService.AbandonRequest request) {
            return base.Channel.Abandon(request);
        }
        
        public void Abandon(TwinfieldApi.TwinfieldSessionService.Header Header) {
            TwinfieldApi.TwinfieldSessionService.AbandonRequest inValue = new TwinfieldApi.TwinfieldSessionService.AbandonRequest();
            inValue.Header = Header;
            TwinfieldApi.TwinfieldSessionService.AbandonResponse retVal = ((TwinfieldApi.TwinfieldSessionService.SessionSoap)(this)).Abandon(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldSessionService.AbandonResponse> TwinfieldApi.TwinfieldSessionService.SessionSoap.AbandonAsync(TwinfieldApi.TwinfieldSessionService.AbandonRequest request) {
            return base.Channel.AbandonAsync(request);
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldSessionService.AbandonResponse> AbandonAsync(TwinfieldApi.TwinfieldSessionService.Header Header) {
            TwinfieldApi.TwinfieldSessionService.AbandonRequest inValue = new TwinfieldApi.TwinfieldSessionService.AbandonRequest();
            inValue.Header = Header;
            return ((TwinfieldApi.TwinfieldSessionService.SessionSoap)(this)).AbandonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldSessionService.GetRoleResponse TwinfieldApi.TwinfieldSessionService.SessionSoap.GetRole(TwinfieldApi.TwinfieldSessionService.GetRoleRequest request) {
            return base.Channel.GetRole(request);
        }
        
        public string GetRole(TwinfieldApi.TwinfieldSessionService.Header Header) {
            TwinfieldApi.TwinfieldSessionService.GetRoleRequest inValue = new TwinfieldApi.TwinfieldSessionService.GetRoleRequest();
            inValue.Header = Header;
            TwinfieldApi.TwinfieldSessionService.GetRoleResponse retVal = ((TwinfieldApi.TwinfieldSessionService.SessionSoap)(this)).GetRole(inValue);
            return retVal.GetRoleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldSessionService.GetRoleResponse> TwinfieldApi.TwinfieldSessionService.SessionSoap.GetRoleAsync(TwinfieldApi.TwinfieldSessionService.GetRoleRequest request) {
            return base.Channel.GetRoleAsync(request);
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldSessionService.GetRoleResponse> GetRoleAsync(TwinfieldApi.TwinfieldSessionService.Header Header) {
            TwinfieldApi.TwinfieldSessionService.GetRoleRequest inValue = new TwinfieldApi.TwinfieldSessionService.GetRoleRequest();
            inValue.Header = Header;
            return ((TwinfieldApi.TwinfieldSessionService.SessionSoap)(this)).GetRoleAsync(inValue);
        }
    }
}
